- og: "Podfast"
- og: "Podfast - Happy Podcasting!"
- og: "Helping people on the go find and choose podcast episodes quickly, by combining flexible search criteria (based on mood) with episode ratings and recommendations information."
- og: "www.podfast.life"
- og: "Podfast.png"
